import React from 'react';
import { Image } from 'react-native';
import { MaterialCommunityIcons, Ionicons } from '@expo/vector-icons';
import { s } from './scale';

// The project's own illustrated icons (assets/icon, generated by
// tools/make-icons.js). These win over the glyph map below.
//
// They are full-colour drawings, so the `color` prop does not apply — tinting
// would flatten them. Anything that needs to change colour with state ships as
// a pair instead: see the nav-*-active / nav-*-inactive entries.
const IMAGES = {
  // 기본 기록
  dog: require('../assets/icon/icon_dog.png'),
  cat: require('../assets/icon/icon_cat.png'),
  meal: require('../assets/icon/icon_food.png'),
  poop: require('../assets/icon/icon_poop.png'),
  pee: require('../assets/icon/icon_urine.png'),
  vomit: require('../assets/icon/icon_vomit.png'),
  condition: require('../assets/icon/icon_condition.png'),
  walk: require('../assets/icon/icon_walk.png'),
  weight: require('../assets/icon/icon_weight.png'),
  healthPhoto: require('../assets/icon/icon_health_photo.png'),
  memo: require('../assets/icon/icon_memo.png'),
  hospital: require('../assets/icon/icon_hospital.png'),
  pill: require('../assets/icon/icon_pill.png'),
  vaccine: require('../assets/icon/icon_syringe.png'),

  // 하단 메뉴 — active/inactive 쌍
  'nav-home-active': require('../assets/icon/icon_nav_home_active.png'),
  'nav-home-inactive': require('../assets/icon/icon_nav_home_inactive.png'),
  'nav-calendar-active': require('../assets/icon/icon_nav_calendar_active.png'),
  'nav-calendar-inactive': require('../assets/icon/icon_nav_calendar_inactive.png'),
  'nav-schedule-active': require('../assets/icon/icon_nav_schedule_active.png'),
  'nav-schedule-inactive': require('../assets/icon/icon_nav_schedule_inactive.png'),
  'nav-stats-active': require('../assets/icon/icon_nav_statistics_active.png'),
  'nav-stats-inactive': require('../assets/icon/icon_nav_statistics_inactive.png'),
  'nav-my-active': require('../assets/icon/icon_nav_mypage_active.png'),
  'nav-my-inactive': require('../assets/icon/icon_nav_mypage_inactive.png'),

  // 일정 종류 (03_DB_Design scheduleType) — 일정 화면에서 쓴다
  'schedule-heartworm': require('../assets/icon/icon_schedule_heartworm.png'),
  'schedule-checkup': require('../assets/icon/icon_schedule_health_checkup.png'),
  'schedule-custom': require('../assets/icon/icon_schedule_manual_input.png'),

  // 준비 중 화면이 쓰는 대표 아이콘
  calendar: require('../assets/icon/icon_nav_calendar_active.png'),
  chart: require('../assets/icon/icon_nav_statistics_active.png'),
  user: require('../assets/icon/icon_nav_mypage_active.png'),
};

// Glyph fallback for UI chrome the icon set doesn't cover (닫기, 화살표, 스텝퍼
// 등). Maps the design's Tabler names to the closest @expo/vector-icons glyph.
// [family, glyph] — 'mci' = MaterialCommunityIcons, 'ion' = Ionicons.
const MAP = {
  dog: ['mci', 'dog'],
  cat: ['mci', 'cat'],
  paw: ['mci', 'paw'],
  meal: ['mci', 'bowl-mix'],
  poop: ['mci', 'emoticon-poop'],
  pee: ['mci', 'water'],
  walk: ['mci', 'walk'],
  vomit: ['mci', 'emoticon-sick-outline'],
  condition: ['mci', 'emoticon-happy-outline'],
  weight: ['mci', 'scale-bathroom'],
  memo: ['mci', 'note-text-outline'],
  camera: ['mci', 'camera-outline'],
  dots: ['mci', 'dots-horizontal'],
  vaccine: ['mci', 'needle'],
  stethoscope: ['mci', 'stethoscope'],
  checks: ['mci', 'check-all'],
  check: ['mci', 'check'],
  bell: ['ion', 'notifications-outline'],
  user: ['ion', 'person-outline'],
  'file-text': ['ion', 'document-text-outline'],
  'message-circle': ['ion', 'chatbubble-ellipses-outline'],
  cake: ['mci', 'cake-variant-outline'],
  venus: ['mci', 'gender-female'],
  plus: ['ion', 'add'],
  minus: ['ion', 'remove'],
  x: ['ion', 'close'],
  'arrow-left': ['ion', 'arrow-back'],
  'chevron-down': ['ion', 'chevron-down'],
  'chevron-up': ['ion', 'chevron-up'],
  'chevron-right': ['ion', 'chevron-forward'],
  'chevron-left': ['ion', 'chevron-back'],
  home: ['ion', 'home'],
  calendar: ['ion', 'calendar-outline'],
  chart: ['ion', 'stats-chart'],
  edit: ['mci', 'pencil-outline'],
};

// `size` is a design-unit number, scaled here so the ~40 call sites can keep
// passing the prototype's values.
export default function Icon({ name, size = 20, color = '#2A2521', style }) {
  const px = s(size);

  const image = IMAGES[name];
  if (image) {
    // `color` is intentionally unused — see the note on IMAGES.
    return (
      <Image
        source={image}
        style={[{ width: px, height: px }, style]}
        resizeMode="contain"
      />
    );
  }

  const entry = MAP[name] || ['mci', 'help-circle-outline'];
  const [family, glyph] = entry;
  const Cmp = family === 'ion' ? Ionicons : MaterialCommunityIcons;
  return <Cmp name={glyph} size={px} color={color} style={style} />;
}
